pub(super) mod abandoned_packages;
pub(super) mod components;
pub(super) mod dependencies;
pub(super) mod header;
pub(super) mod license_compliance;
pub(super) mod non_pypi_packages;
pub(super) mod python_compatibility;
pub(super) mod resolution_guide;
pub(super) mod summary;
